metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "auto"

replication_factor = 1

[s3_api]
s3_region = "garage"
bind_addr = "0.0.0.0:3900"

[admin]
bind_addr = "0.0.0.0:3903"
